### ISSUE TITLE
本地图片带尺寸的后缀时，上传会失败，显示“没有解析到图像文件”

### ISSUE THREAD

**Issue by ohownew** [renmu123/obsidian-image-auto-upload-plugin#102]
![image](https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/17061417/c1affe24-374d-44d5-81de-884c5010f3da)

![image](https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/17061417/8a11ae68-46c6-4fdb-9381-c648203e6e97)

**Comment by cumany** [comment]
+1
比如 源文件为 ![[xxxx.png|cover]] 图片实际被命名为cover，希望上传后仍然保留cover名称 ![cover](xxxx.png)
