### ISSUE TITLE
PicGo-Core上传失败

### ISSUE THREAD

**Issue by Hsdf1234** [renmu123/obsidian-image-auto-upload-plugin#103]
相同的 PicGo-Core 配置，在 Typora 上能够成功上传图床，而用 Obsidian 则上传失败。
Obsidian：
![image](https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/100564236/62ffcb38-f47a-4be6-9c60-e05ae42f2876)
Typora：
![image](https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/100564236/56dcbd32-f23d-4d6e-bb49-4dcb905ce8ac)
已经确定 PicGo-Core 路径无误

**Comment by renmu123** [comment]
3.5.0我尝试性更新了一下，你试试看粘贴时能不能自动上传（批量上传我没改），我还是不知道为什么会出现这种情况

**Comment by Jovendish** [comment]
在3.5.0版本中遇到同样问题
![image](https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/25397930/5cfa7ee1-7aba-42b6-a238-5efa94dcbf17)

**Comment by Hsdf1234** [comment]
> 3.5.0我尝试性更新了一下，你试试看粘贴时能不能自动上传（批量上传我没改），我还是不知道为什么会出现这种情况
![48a4008806284013647588979865dca](https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/100564236/227e0c67-9774-4020-af48-1a2c4f56d2e1)
现在的问题更迷惑了，我转战 Imgur 了，感觉简单了不少，直接就配置成功了
