### ISSUE TITLE
网络图片域名黑名单问题

### ISSUE THREAD

**Issue by wukong999** [renmu123/obsidian-image-auto-upload-plugin#105]
感谢大佬提供的插件！
求教一下，我是自己搭建的图床，上传图片之后，如果复制就会重复上传该图片，看到插件设置里面有网络图片域名黑名单功能，输入了我的服务器地址，为什么不生效那（我输入的是http://015144.xyz:9495和https://zhuanlan.zhihu.com/都不可以）？求教是为什么那

**Comment by renmu123** [comment]
不需要携带协议或者端口号，设置为`zhuanlan.zhihu.com`就可以了
