### ISSUE TITLE
上传图片显示⚠️upload failed, check dev console和Cannot read properties of undefined (reading '0')  

### ISSUE THREAD

**Issue by 410463305** [renmu123/obsidian-image-auto-upload-plugin#106]
![image](https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/1077729/5bcaeea0-fee5-4941-9807-ce75852854de)

obsidian: 1.3.7
picgo: 2.3.1和2.4.0beta3都试过
obsidian-image-auto-upload-plugin: 3.6.0
没试过typora
windows11家庭版

**Comment by 410463305** [comment]
我又测试了一下：
1.直接插入网络图片地址`![](https://xxx.com/xxx.png)`，然后用插件的命令upload all images，可以把网络图片上传给picgo，并且用picgo返回的网址替换了网络图片地址
2.保存图片到本地目录再插入本地地址`![](D:\xxx\xxx.png)`，然后用插件的命令upload all images，提示upload error，图片没有上传给picgo
![](https://img1.imgtp.com/2023/08/07/mPzLNbbR.png)
3.复制图片再直接粘贴插入，提示⚠️upload failed, check dev console和Cannot read properties of undefined (reading '0')，图片没有上传给picgo

**Comment by JunDecNo** [comment]
关闭代理软件就可以了. 我的是这个问题

**Comment by mmdzt** [comment]
> 关闭代理软件就可以了. 我的是这个问题

关闭代理也没用😭

**Comment by kirin521** [comment]
同样的错误，关不关代理都没有用。。

**Comment by ease-zh** [comment]
同样的错误。
控制台显式错误信息为：
![image](https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/28568749/4ce7bbf7-b488-4811-b20e-0530aa117c65)

**Comment by mmdzt** [comment]
我后来重新截图上传就没问题了，因为我用Alfred可以加载历史复制记录，用Alfred重新加载复制的内容再上传也不会出问题。不知道是不是格式之类的原因。

**Comment by renmu123** [comment]
尝试在picgo的设置中切换“使用内置剪切板上传”设置，如果是linux系统，请确保没有缺少依赖

**Comment by renmu123** [comment]
> .直接插入网络图片地址`![](https://xxx.com/xxx.png)`，然后用插件的命令upload all images，可以把网络图片上传给picgo，并且用picgo返回的网址替换了网络图片地址

不支持这种绝对路径的文件，我想问问你们这些绝对路径的文件是哪里来的，ob不是会自动转换为基于库的相对路径的吗？

**Comment by 410463305** [comment]
close

**Comment by renmu123** [comment]
> 好吧，我看了一下piclist的日志，是因为找不到要上传的图片而报错的 我的piclist安装在服务器电脑上，obsidian在个人电脑上，两者不在同一个系统 我的obsidian仓库也存在服务器上，我是通过将服务器目录挂载到个人电脑上而使用obsidian的 而插件没有考虑到这种情况 如此，在直接复制粘贴图片上传时，插件告诉piclist server图片在剪切板中 ![image](https://user-images.githubusercontent.com/1077729/265477972-ad4e7f78-0554-4a24-8daa-4e27fa66a525.png) 而先贴图片再用命令上传，插件传了图片的地址（\ip\PATH\picture.png)到piclist server ![image](https://user-images.githubusercontent.com/1077729/265478410-a3237950-cfa2-4607-bbe9-5964d8d93686.png) 而贴网络图片地址时，piclist会去相应的网址下载图片，就没有问题
> 
> 我看到您在issue #77
> 
> > 理论上你可以在服务器运行picgo，只要通过命令行来编辑配置文件后运行就可以了，监听地址修改为0.0.0.0。
> > 我实际没有尝试过，你可以开个issue去PicGo作者那里问问
> 
> 实测应该是不行的 比较奇怪为什么不直接发送图片到server呢？另外在日志中我看到piclist有另外一个端口是36699的File server，还不清楚是什么作用

我想了一下确实是不支持的，因为剪贴板上传的是当前电脑中剪切板的文件，批量上传传递的参数是本地图片的绝对路径，那么piclist不能上传是正常的

**Comment by Sincejunly** [comment]
> 关闭代理软件就可以了. 我的是这个问题

picgo自己能上传，这个插件受代理影响，很奇怪

**Comment by shaofeer** [comment]
MAC电脑：看报错是这样
Error: ENOENT: no such file or directory, open '/Users/xxxxx/Library/Application Support/picgo/picgo-clipboard-images/202506162343108.png.3212715339'

然后我发现 `picgo-clipboard-images` 这个文件夹不存在，所以`mkdir picgo-clipboard-images`新建了一个文件夹就可以了
