### ISSUE TITLE
请求添加PicList的跨电脑上传支持

### ISSUE THREAD

**Issue by Kuingsmile** [renmu123/obsidian-image-auto-upload-plugin#113]
根据 https://github.com/Kuingsmile/PicList/issues/103 目前PicList和PicList-Core都已经支持了表单上传feature，使用方式为`content-type`设置为`multipart/form-data`，表单字段目前可任意设置，但推荐为`files`，返回值与原接口相同。

目前直接跨电脑使用时，由于还是通过传`list`字段的文件路径发送请求，或者不带body体默认上传剪贴板文件，都会失败报错，应该可以判断接口host，不是`127.0.0.1`的时候，采用表单上传来进行适配，从而支持跨电脑上传。

**Comment by renmu123** [comment]
其实是我提的issue，还没做完适配，还要个几天

**Comment by Kuingsmile** [comment]
一开始就发现是你提的了 反向提回来 哈哈哈 😆

**Comment by renmu123** [comment]
![image](https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/26896790/c0db4ae3-d5ef-4e60-a49a-0864860f3792)
我觉得`config`字段不应该返回详细配置，不然安全性太低了，要么做一层加密，实在是不应该明文传输

**Comment by Kuingsmile** [comment]
> ![image](https://user-images.githubusercontent.com/26896790/275731929-c0db4ae3-d5ef-4e60-a49a-0864860f3792.png) 我觉得`config`字段不应该返回详细配置，不然安全性太低了，要么做一层加密，实在是不应该明文传输

返回详细配置主要是可以不依赖接口接收端的数据库或者保存的配置信息，做一层加密应该是可以的，我修一下
