### ISSUE TITLE
关于图片上传后丢失本地图片路径的问题

### ISSUE THREAD

**Issue by Asahey** [renmu123/obsidian-image-auto-upload-plugin#115]
我没有勾选“上传文件后移除源文件”，但是发现当我把图片上传到图床后，原来的路径变成了图床的url，而仍保留在本地的图片的路径直接丢失了。
  这相当于“上传文件后移除源文件”这个选项根本没有意义，因为只要上传后本地的图片路径就必然找不到了，只能用从图床重新下载。而如果图床炸了，即使本地有图片备份，笔记中的所有图片映射仍然会全部丢失。
   
  如图，当图床文件丢失后，即使我本地存有709na这个文件，下载功能也无法使用。
![image](https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/71593487/26c0fa23-8288-4f7c-8ee0-9990fde923f3)
  但是我可以手动改名来找回
![image](https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/71593487/6a905541-145c-4834-b683-6a7ed5036824)

  我的建议是，当用户没有勾选“上传文件后移除源文件”，上传图片时除了把链接变成图床链接，还应保存原有的本地图片路径，这样使用下载功能时不用再从图床下载，直接把路径改回之前存储的本地路径即可。

**Comment by renmu123** [comment]
“上传图片后移除源文件”值的是在你上传图片后删除原始文件。
下载功能指得是从图床下载图片到本地，你图床文件挂了，自然无法下载。这是一个完全独立的功能。
我也不建议使用这种不稳定的图床。
