### ISSUE TITLE
粘贴图片后，自动替换的是 ![](h)，没有替换成剪切板的链接

### ISSUE THREAD

**Issue by 2622019635** [renmu123/obsidian-image-auto-upload-plugin#12]

**Comment by renmu123** [comment]
提供一下插件版本，ob版本，picgo版本。
ob 0.13.14版本的话需要升级插件到最新版。

picgo 2.3.0-beta7有bug，需要升级

**Comment by jt-z** [comment]
升级picgo和这个插件后正常了

**Comment by 2622019635** [comment]
是的，问题来源于 picgo 2.3.0-beta7，更新到 picgo 2.3.0 就好了
