### ISSUE TITLE
piclist的云端删除功能怎么用

### ISSUE THREAD

**Issue by NianLee0** [renmu123/obsidian-image-auto-upload-plugin#122]
如题，如果只是把链接删除并不会删除云端图片，作者能具体讲讲怎么使用这一功能吗

**Comment by Kuingsmile** [comment]
> 如题，如果只是把链接删除并不会删除云端图片，作者能具体讲讲怎么使用这一功能吗

选中完整的链接，右键会出现新的选项"使用PicList删除"，用这个选项会触发云端删除。直接删除不会触发是出于避免误删除的考虑。

**Comment by NianLee0** [comment]
感谢感谢
