### ISSUE TITLE
破坏了本地链接功能

### ISSUE THREAD

**Issue by jiajiala** [renmu123/obsidian-image-auto-upload-plugin#129]
当我按住 ctrl 拖动 psd 文件到 ob 中的时候，原本的操作应该是产生一个本地链接
但插件 会将我的 psd 上传，然后返回我一个无法显示的链接

1 这个BUG破坏了本地链接的功能，让我无法使用本地链接图片
2 以及PSD这种无需上传到图床的文件也会被上传到图床中

**Comment by renmu123** [comment]
重复 #147
