### ISSUE TITLE
配合PicGo 2.3.1-beta.2，原始文件名返回位置不正确

### ISSUE THREAD

**Issue by kamusis** [renmu123/obsidian-image-auto-upload-plugin#13]
之前是返回：
```![](https://s2.loli.net/2022/01/07/GsmMoPAQbq5N67D.jpg)```
现在paste图片之后返回的是：
```
![](https://s2.loli.net/2022/01/07/GsmMoPAQbq5N67D.jpg)
日本战国大名割据图.jpg
```

原始文件名放在了链接的下一行。而通常这在文章里是没有用处的。

建议：
1. 可以不返回原始文件名，保持跟之前版本一样
2. 将原始文件名放入[]之中，作为图片alt也行，但是如果这样操作，建议去掉原始文件扩展名，只保留扩展名之前的文件名称，如：
```![日本战国大名割据图](https://s2.loli.net/2022/01/07/GsmMoPAQbq5N67D.jpg)```

**Comment by renmu123** [comment]
你是用的 `upload all imgaes` 吗？我更新了picgo版本，没办法复现

**Comment by kamusis** [comment]
就是常规的操作，截图到剪贴板（我用的iShot），然后Cmd+V粘贴到Obsidian。
而且今天发现了更严重的问题，Obsidian升级到了0.13.19，新增了直接preview的功能，目前看图片都无法自动upload了。

**Comment by renmu123** [comment]
更新插件至最新版

**Comment by kamusis** [comment]
👍 It works!
