### ISSUE TITLE
剪贴板图片上传失败

### ISSUE THREAD

**Issue by ybubuzi** [renmu123/obsidian-image-auto-upload-plugin#133]
```js
⚠️upload failed, check dev console
⚠️upload failed, check dev console
```

**Comment by ybubuzi** [comment]
造成的原因：
怀疑是PicGo运行在后台，系统托盘存在PicGo的图标的时候，调用命令行不会正确返回上传文件

![image](https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/102141781/59b25a33-661b-4c61-a27c-b264f1a68b32)

解决办法：
关闭后台的PicGo.exe

PicGo版本：2.3.1

**Comment by guoyuejiang** [comment]
你好，我用的是2.4.0-beta.8，也有这个问题，请问关闭后台的picgo.exe是怎么操作呢？picgo在后台会产生3~6个进程，关掉以后picgo的server服务也掉了
