### ISSUE TITLE
Markdown标准标签无法识别

### ISSUE THREAD

**Issue by yw1573** [renmu123/obsidian-image-auto-upload-plugin#143]
![image](https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/42687512/12901823-11bd-4071-bd20-f8ff5b27732d)
这类标签无法识别，希望作者大佬给与支持

**Comment by breakstar** [comment]
我也遇到了类似的问题，剪藏的md文件有如下格式，在ob中使用命令行上传全部的时候，无法识别这种情况。希望作者给与支持。谢谢！
```
![在系统资源管理器中显示](assets/show-in-file-explore_201f0b12526b4ae224929abb1f9be683.png "在系统资源管理器中显示")
```

**Comment by renmu123** [comment]
closed https://github.com/renmu123/obsidian-image-auto-upload-plugin/commit/39ab425a0d3add7ea5f7b491e520dcbab3b0e413
