### ISSUE TITLE
希望有办法不上传obsidian库外的本地链接的图片

### ISSUE THREAD

**Issue by jiajiala** [renmu123/obsidian-image-auto-upload-plugin#147]
因为库外的本地链接的图片并不希望被上传到网络上
需要其保持本地的状态
但是只要开启插件，无论是obsidian库内的图片还是库外的都会被上传
希望有办法能够屏蔽掉库外的图片

**Comment by fieri** [comment]
有时候是需要这个功能的，最好做成选项，可以开关此功能

**Comment by jiajiala** [comment]
这个插件还在更新么，求可以选择不上传本地 file:/// 链接的图片

**Comment by renmu123** [comment]
#63 你和这几个打一架，我印象中是只支持上传库内的图片的，请提供更多信息，比如系统，比如最小复现文档

**Comment by jiajiala** [comment]
> #63 你和这几个打一架，我印象中是只支持上传库内的图片的，请提供更多信息，比如系统，比如最小复现文档

![9](https://github.com/user-attachments/assets/05c8568c-f357-4261-ac05-555167014966)
![image](https://github.com/user-attachments/assets/11e4c9d1-668b-48cc-bc0d-7ea73c5a99df)
我按住ctrl+拖动本地图片到obsidian，拖动结束后，图片被上传到了E:\Killer_Project\Killer_OB\tuku\1
![image](https://github.com/user-attachments/assets/2e4e2b74-744c-4af7-abd0-5ac066c1d2d2)
本来挺好的，通过这个插件我可以将obsidian的图片全都放到本地，只需要将剪贴板图片黏贴到obsidian中，文件就自动会上传到对应的本地文件夹，但是发现会将我拖动的本地文件也上传

**Comment by jiajiala** [comment]
如果有其他人有这个上传的需求，是不是可以有一个选项，选择是否要上传本地超链接文件
因为很多文件是要本地被其他文件使用，无法上传的，并不想每个文件都上传到网络

**Comment by renmu123** [comment]
closed https://github.com/renmu123/obsidian-image-auto-upload-plugin/commit/818a91e997ca1ecf4e14b883247be63f07c55357

**Comment by jiajiala** [comment]
大佬有没有修复了这个BUG的版本可以用otz

**Comment by renmu123** [comment]
> 大佬有没有修复了这个BUG的版本可以用otz

你可以尝试自己编译 4.0.0，预计正式版下周会发布

**Comment by renmu123** [comment]
4.0.0已经发布
