### ISSUE TITLE
对粘贴的图片希望可以自动改名字

### ISSUE THREAD

**Issue by zen010101** [renmu123/obsidian-image-auto-upload-plugin#153]
因为我是使用 Nextcloud 作为图床，而 PicList 每次对粘贴都是用 Image.png 这个名字，造成 Nextcloud中查看，这些文件是一个图片，只是不同的的版本。

![image](https://github.com/user-attachments/assets/25d46d14-af80-46fe-b196-16302839ea7c)

**Comment by renmu123** [comment]
你应该去piclist去提issue，或者在piclist设置里使用时间戳或其他重命名方式
