### ISSUE TITLE
服务器端运行piclist，执行上传完成后获取图片链接失败

### ISSUE THREAD

**Issue by TAT-Hins** [renmu123/obsidian-image-auto-upload-plugin#155]
## 操作步骤

- 服务器端通过docker安装piclist（[参考链接](https://github.com/Kuingsmile/PicList/blob/dev/README_cn.md#%E5%A6%82%E4%BD%95%E5%9C%A8docker%E4%B8%AD%E4%BD%BF%E7%94%A8)）

- 在设置中设定插件通过服务器部署的picgo/piclist CLI提供的http接口进行上传，服务器端内网IP为192.168.2.154，提供服务端口保持为36677
  ![image](https://github.com/user-attachments/assets/af395bfe-0106-4ca8-a339-4d9c64286fc2)

## 结果

- 通过Windows自带照片查看器进行复制，在Obsidian中Ctrl+V粘贴后可以正常执行上传，但是无法从服务器端获取返回的照片上传图床后的链接，文档中显示为null
  ![image](https://github.com/user-attachments/assets/2ab9cb1c-730f-4b05-bf26-64b717605fa1)
  - 通过图床相册管理，可以确认照片上传触发成功

- 通过本机安装的picgo/piclist进行上传的话则一切正常

## 疑问

- 不清楚是piclist docker版本身存在无法返回链接的情况，还是通过docker仅映射36677端口无法正常获取并复制上传后的链接，希望请教有此经验的朋友

**Comment by renmu123** [comment]
我测试的时候遇到过这种情况，修改配置后可能需要重启docker服务才能完全生效，如果还是有问题，去piclist去提问

**Comment by TAT-Hins** [comment]
> 我测试的时候遇到过这种情况，修改配置后可能需要重启docker服务才能完全生效，如果还是有问题，去piclist去提问

OK，感谢，通过PicList设置之后已经work了
