### ISSUE TITLE
没有解析到图像文件

### ISSUE THREAD

**Issue by sanwacompany** [renmu123/obsidian-image-auto-upload-plugin#156]
如图，应该已经按照设置说明设置了。请问是什么原因？
![微信截图_20241007130204](https://github.com/user-attachments/assets/69ab9bd8-8353-4ed5-af1f-b11c651295f4)
![微信截图_20241007130217](https://github.com/user-attachments/assets/8bcbf3f8-c685-43bf-b820-0ed9a937ccbf)
![微信截图_20241007130248](https://github.com/user-attachments/assets/16361a38-2c60-48d3-9bdb-77dc7bfcea4b)
![微信截图_20241007130317](https://github.com/user-attachments/assets/c4cdb6bd-b3af-4ab2-b82c-701f19b58d23)

**Comment by renmu123** [comment]
close in https://github.com/renmu123/obsidian-image-auto-upload-plugin/commit/235c7400581ee0ad2c54709eee35bfe1d0069f4a
