### ISSUE TITLE
作者大大实在是太牛了，考虑过给思源笔记做一个picgo插件嘛？

### ISSUE THREAD

**Issue by LZ7-owo** [renmu123/obsidian-image-auto-upload-plugin#158]
我是这个插件的忠实用户，之前使用obsidian，这个插件体验非常好！！！
现在转用思源，思源也有第三方自制的picgo插件，但是我经常上传失败……体验比你的插件差太远了（哀嚎），你甚至还提供一键全部上传图片的指令！！希望大佬能来拯救一下卑微的思源用户，许愿ing

**Comment by renmu123** [comment]
暂时没有打算，如果我哪天也迁移到思源了，可能会做~
