### ISSUE TITLE
为什么装了最新版本还是会上传好多个文件

### ISSUE THREAD

**Issue by 1205129045x** [renmu123/obsidian-image-auto-upload-plugin#18]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/50540240/150948025-4afb1a3e-cdf0-4045-b35b-22cdcf20ee5a.png">
插件就是最新的2.0.0

**Comment by renmu123** [comment]
你重启一下obsidian看一下

**Comment by 1205129045x** [comment]
> 你重启一下obsidian看一下

可以了，谢谢大佬
