### ISSUE TITLE
Bug：粘贴docx、mp3等非图片格式时，也会自动上传

### ISSUE THREAD

**Issue by tyf2018** [renmu123/obsidian-image-auto-upload-plugin#19]
谢谢开发出这么实用的插件，我想反馈使用过程中遇到的两个小问题：

1. 粘贴docx、mp3等非图片格式时，也会自动上传，请问是我设置有误吗？
2. 另外Image auto upload Plugin: upload all images这个命令，一直不生效。

**Comment by megatree** [comment]
确实，我也遇到了。。

**Comment by bigsong611** [comment]
我也遇到，希望修复一下

**Comment by renmu123** [comment]
更新到最新版本试试看

https://github.com/renmu123/obsidian-image-auto-upload-plugin/issues/16

**Comment by CarlSongcs** [comment]
感谢作者，现在拖拽已经正常了，可是复制依然存在同样的问题

**Comment by renmu123** [comment]
> 感谢作者，现在拖拽已经正常了，可是复制依然存在同样的问题

不知道你是什么版本，我不能复现

**Comment by snail123815** [comment]
我装了Excel to Markdown Table, 粘贴excel时也会上传一张表格截图。

![image](https://user-images.githubusercontent.com/9590933/194287231-8fba713e-0e96-4cf1-adaf-e705a0493262.png)

```
SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.15.9
	Operating system: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 21.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Typomagical
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 4
	Plugins enabled: 4
		1: Vimrc Support v0.7.3
		2: Image auto upload Plugin v2.6.1
		3: Advanced Tables v0.17.3
		4: Excel to Markdown Table v0.4.0
```

**Comment by renmu123** [comment]
确实有这个问题，原因是Chromium内核不知道哪次更新之后可以直接获取到系统图片的data了，导致判断出了问题（其实主要是一个逻辑判断本来就有问题2333）。
Win是没问题了，Mac没测试不好说，有问题再提issue吧
