### ISSUE TITLE
After pasting, it turn to ![](h) instead of ![](github.com/…)

### ISSUE THREAD

**Issue by Tylerrrrrrr007** [renmu123/obsidian-image-auto-upload-plugin#2]
I have configured it correctly.
After pasting, it turn to ![](h) instead of ![](github.com/…)
Then I pasted again, it appeared in the correct format.

Therefore, I have to paste twice and delete once; otherwise, I have to ctrl+v+z+v.
What's going on?

**Comment by renmu123** [comment]
it will be fixed in 2.3.0-beta.8 version

**Comment by Tylerrrrrrr007** [comment]
ok, thank you
