### ISSUE TITLE
点击批量上传没有任何反应

### ISSUE THREAD

**Issue by 1657744680** [renmu123/obsidian-image-auto-upload-plugin#24]
操作系统：win11
obsidian版本：0.13.33
插件版本：2.0.1

md文档中图片链接格式：`![](attachments/mmexport1647550439670.jpg)`
采用的是相对链接格式。

bug：在命令面板选择批量上传命令，但是没有任何响应，obsidian控制台没有任何提示，picgo日志文件也没有看到任何痕迹。

**Comment by Gnblink0** [comment]
我也遇到了这种情况，可能是这个让我以为出错了，才会误以为上传是上传全库……

**Comment by renmu123** [comment]
#32
