### ISSUE TITLE
关于两个更精细的上传粒度的建议

### ISSUE THREAD

**Issue by Gnblink0** [renmu123/obsidian-image-auto-upload-plugin#28]
首先，感谢开发如此棒的插件，对ob的图片体验改善很有用！
我有写相关文章提到它：[有关 Markdown 中的图片，你需要知道的一切](https://shutgnblink.me/2022/%E6%9C%89%E5%85%B3markdown%E4%B8%AD%E7%9A%84%E5%9B%BE%E7%89%87%E4%BD%A0%E9%9C%80%E8%A6%81%E7%9F%A5%E9%81%93%E7%9A%84%E4%B8%80%E5%88%87/)

希望可以增加两个功能，以实现除了 全库上传 和 自动上传 外更精细的图片上传粒度
1. 只上传本页图片
下载图片到本地插件（local images），就有此功能
我基本不敢点全库图片上传……也看到已经有人提了类似建议：[能否增加单独在一篇文章中上传或者下载的功能 · Issue #22 · renmu123/obsidian-image-auto-upload-plugin](https://github.com/renmu123/obsidian-image-auto-upload-plugin/issues/22)

2. 快捷键上传光标贴近的图片
自动抓取链接标题插件（Auto Link Title），就有此功能
[zolrath/obsidian-auto-link-title: Automatically fetch the titles of pasted links](https://github.com/zolrath/obsidian-auto-link-title)

如果真的能更新，ob的本地、外链图片互转功能就几乎完美了，再次感谢开发者！

**Comment by renmu123** [comment]
1. 一直都有上传本页图片，倒是没有全库图片上传的功能
2. 鼠标右键本地图片链接，可以直接上传，但是新版本中出了一个bug，暂时不能用
