### ISSUE TITLE
Is it possible to upload images without PicGo being opened?

### ISSUE THREAD

**Issue by zcysxy** [renmu123/obsidian-image-auto-upload-plugin#3]
Thanks for this nice plugin!

Just as the title says, now you need to keep PicGo running to upload images from Obsidian. Is it possible to upload images without PicGo being opened? I use another extension called PicGo on VS Code and it is able to achieve this.

**Comment by renmu123** [comment]
The ![vs-picgo](https://github.com/PicGo/vs-picgo) plugin use  picgo-core, a CLI.

Pic-core support is in TODO.
#4

**Comment by renmu123** [comment]
Now picgo-core has been supported
