### ISSUE TITLE
download图片命名问题

### ISSUE THREAD

**Issue by allworldg** [renmu123/obsidian-image-auto-upload-plugin#31]
能否自定义设置下载图片的命名格式，如果按照默认插件格式，下载后图片链接为![image](https://user-images.githubusercontent.com/48782874/165714752-59f342e4-5ec8-4513-a855-c2538e255490.png)，可是[]里面如果是纯数字，则代表该图片的图像浏览大小，这就会导致十分大。

**Comment by allworldg** [comment]
刚多试了几次，发现好像命名是纯随机的？有一点点不太方便

**Comment by CarlSongcs** [comment]
同样的问题，希望能够得到答复

**Comment by renmu123** [comment]
可以是可以，但这个bug其实是ob最近几个版本引入的，不是我的锅，我稍后更新一下

**Comment by renmu123** [comment]
cloese
