### ISSUE TITLE
uploadAll相对路径无法上传

### ISSUE THREAD

**Issue by allworldg** [renmu123/obsidian-image-auto-upload-plugin#33]
其实对于 #32 的修改，只是简单判断是否.开头来判断相对路径反而造成了我相对路径无法上传的问题，这是我的结构
![image](https://user-images.githubusercontent.com/48782874/171346989-634bcaab-932d-4e99-9c82-894f0bdf3729.png)
这是我的路径，`images/Pasted%20image%2020220526165445.png`,同级或者是子相对路径是不会添加 `.` 的。

![image](https://user-images.githubusercontent.com/48782874/171347378-10c32786-2233-40d9-9b7e-21cae4c6b149.png)

**Comment by renmu123** [comment]
你是设置“新附件的默认位置”为“当前文件夹下的指定子文件夹中”了吗？

如果设置“内部链接类型”为“基于库的绝对路径”，新附件的默认位置为“下方指定文件夹”。

这个设置和你的设置生成的文件路径是一样的，两个都是合法的，也不太好判断。我觉得这是ob的设计失误。

要么就整个开关，你们自己来选是绝对路径还是相对路径

**Comment by renmu123** [comment]
https://github.com/renmu123/obsidian-image-auto-upload-plugin/commit/39a01d4719660be302b2595f2a7548cc2c0723f2

**Comment by allworldg** [comment]
> 你是设置“新附件的默认位置”为“当前文件夹下的指定子文件夹中”了吗？
> 
> 如果设置“内部链接类型”为“基于库的绝对路径”，新附件的默认位置为“下方指定文件夹”。
> 
> 这个设置和你的设置生成的文件路径是一样的，两个都是合法的，也不太好判断。我觉得这是ob的设计失误。
> 
> 要么就整个开关，你们自己来选是绝对路径还是相对路径

对的，因为上个版本绝对路径不是有bug吗，所以我就改成这样了。整个开关不错，暴力简单
