### ISSUE TITLE
可否增加一个 “对网络位置的图片应用上传规则” 的功能

### ISSUE THREAD

**Issue by silence** [renmu123/obsidian-image-auto-upload-plugin#34]
![image](https://user-images.githubusercontent.com/25074202/171777668-c9206462-ad72-461f-b3ee-bfaf64624e74.png)
如 Typora，可以将粘贴的网络图片链接自动上传。如下：

https://user-images.githubusercontent.com/25074202/171778041-eda82334-b04a-4190-9c1a-1a8b49068cf4.mp4

还有一个小的 feature request. 如视频中，Typora 可以保留图片的 Alt text 信息 "Home-University of Toronto"，不知这个可否做到

**Comment by zcysxy** [comment]
+1

**Comment by jy324** [comment]
+1

**Comment by silence** [comment]
> 已经支持复制后自动替换网络图片链接，接下来还会针对这个功能做个黑名单。~今天下班了~

啊感谢支持！

**Comment by jy324** [comment]
感谢👍
