### ISSUE TITLE
无法安装插件Obsidian Image Auto Upload Plugin

### ISSUE THREAD

**Issue by Kewbing** [renmu123/obsidian-image-auto-upload-plugin#35]
2.2.1版本最近提示无法安装插件Obsidian Image Auto Upload Plugin

**Comment by allworldg** [comment]
+1

**Comment by kindlove3218** [comment]
我关闭了以后，都显示无法打开了。。。。

**Comment by kindlove3218** [comment]
![](https://siyaloobsi.oss-cn-hangzhou.aliyuncs.com/img/202206090648918.png)

**Comment by neilxu1** [comment]
+1，求修复

**Comment by edwards19900128** [comment]
+1， 同无法安装了...

**Comment by lifesign** [comment]
+1

**Comment by Palvehelmed** [comment]
> 我关闭了以后，都显示无法打开了。。。。

我没关也打不开了。

**Comment by cyddgh** [comment]
+1，同样无法安装

**Comment by BILY5354** [comment]
+1 win10没办法安装

**Comment by zjpzhao** [comment]
+1 win10端同样无法安装

**Comment by david50889** [comment]
+1 win11 同样无法安装

**Comment by MugenLee** [comment]
@renmu123
 pls check it
so many people have this problem

**Comment by renmu123** [comment]
已修复，忘记更新最新版本的release了
