### ISSUE TITLE
上传图片是否可以支持自定义命令？

### ISSUE THREAD

**Issue by ryzzn** [renmu123/obsidian-image-auto-upload-plugin#4]
之前用的typera支持自定义命令，所以用了命令行的picgo上传图片到oss，这样就不用打开picgo的界面了。

供参考：

![image](https://user-images.githubusercontent.com/431968/136540439-8dad0eb0-56b4-4c4f-80b9-ee2ae17c3e9b.png)

**Comment by kamusis** [comment]
我看到其他人也有提到说是否可以支持命令行，这样就不用打开PicGo界面，有些疑惑，不知道是不是我理解的不对。
我的理解里，这似乎完全没有困扰，PicGo只要设置了开机启动，其实就是一直可以在后台运行（无非是状态栏里有一个图标），无论Typora还是Obsidian都可以直接调用PicGo，完全不需要手动打开任何界面。

**Comment by renmu123** [comment]
typora分两种上传方式：
一种是pic-core这是纯命令行的，本体要用node进行安装，配置起来也比较麻烦，我就没做支持，优点是占用小。

第二种就是pic-go客户端，这里我和typora是用了相同的方式实现的，都需要pic-go常驻后台，优点是配置简单，缺点是相对占用资源多一些。

**Comment by SzHeJason** [comment]
作者是不是不维护了啊~~ 等我有空搞一个 下载 picgo 这个方法效率太低了

**Comment by renmu123** [comment]
> 作者是不是不维护了啊~~ 等我有空搞一个 下载 picgo 这个方法效率太低了

欢迎，最近太忙了

**Comment by renmu123** [comment]
目前部分功能支持 PicGo-Core
