### ISSUE TITLE
Feature Request: 图片上传后替换本地链接, 并删除本地文件

### ISSUE THREAD

**Issue by zcysxy** [renmu123/obsidian-image-auto-upload-plugin#40]
谢谢开发这个插件! 现在在笔记中右键上传一张本地图片, 只会把图床链接复制到剪贴板. 能否增加一个功能/选项以完成以下工作流

1. 右键上传本地图片
2. 将本地链接替换为图床链接
3. 删除本地文件

**Comment by allworldg** [comment]
@zcysxy ob有自动清理无用链接的插件,偶尔用一次就行.

**Comment by renmu123** [comment]
这个插件不会去做删除等操作的
使用标准md图片链接是会自动替换的，ob专用的wiki链接不行，当时好像是有什么技术问题我才没做的。

**Comment by renmu123** [comment]
目前只是支持以相对路径插入的md标准格式图片

**Comment by renmu123** [comment]
已经更新了，有个设置选项需要设置你是根据绝对路径还是相对路径插入的图片链接。你也可以选择`auto`来跟随应用设置
