### ISSUE TITLE
插件无法解析PicGo上传成功后的图片url链接，导致无法生成正确的markdown图片链接

### ISSUE THREAD

**Issue by shioshoYin** [renmu123/obsidian-image-auto-upload-plugin#42]
<img width="641" alt="image" src="https://user-images.githubusercontent.com/112226436/187027183-c75007c5-f057-45f1-b6c4-9a0dd52bbda0.png">

**Comment by shioshoYin** [comment]
> <img alt="image" width="641" src="https://user-images.githubusercontent.com/112226436/187027183-c75007c5-f057-45f1-b6c4-9a0dd52bbda0.png">

问题根因已定位清楚：

在使用一些特殊的图床时，PicGo返回的data.result是一个字符串(图床url)，而非一个数组。 这导致image auto plugin在使用data.result[0]获取图片url时候，获取不到正确的地址，从而没办法生成markdown的image link，导致无法正确显示图片。

<img width="663" alt="image" src="https://user-images.githubusercontent.com/112226436/187027254-22b3264c-cd38-4409-ad8c-84c5a620ecbb.png">

**Comment by renmu123** [comment]
哪些图床会返回单个参数？那么这种图床没办法同时上传多个图片了？我感觉是picgo那边代码的问题了

**Comment by shioshoYin** [comment]
> 哪些图床会返回单个参数？那么这种图床没办法同时上传多个图片了？我感觉是picgo那边代码的问题了

公司内部使用的图床，在console里面debug了一下，确实是返回了单个字符串。 我在你的插件源码里面做了简单的适配，不影响你代码的功能。 已经提了一个Pull Request。 你看是否考虑能够合入？
