### ISSUE TITLE
上传本地图片时，显示“没有解析到图像文件”

### ISSUE THREAD

**Issue by juncaijames** [renmu123/obsidian-image-auto-upload-plugin#47]
如图(右上角)

![Untitled](https://user-images.githubusercontent.com/18064672/190832566-c77b818c-ca27-458d-8b94-b7b02ed6da4e.png)

**Comment by renmu123** [comment]
贴一下图片在笔记中的链接形式，是标准md还是wiki。你用源码模式截一下图，再提供一下“文件与链接”中配置项

**Comment by xiuqiang1995** [comment]
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/52337226/202846209-f9e9db4d-f0b5-4bf4-8d78-557288ae1e24.png">
<img width="831" alt="image" src="https://user-images.githubusercontent.com/52337226/202846224-8f7f7e1d-998a-4bb0-9c3f-4a5cad1834b9.png">
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/52337226/202846236-483d0f60-0f0e-4407-bb72-033aa438e624.png">

链接形式：![[Pasted image 20221119182548.png]] @renmu123

**Comment by renmu123** [comment]
> <img alt="image" width="1126" src="https://user-images.githubusercontent.com/52337226/202846209-f9e9db4d-f0b5-4bf4-8d78-557288ae1e24.png">
> 
> <img alt="image" width="831" src="https://user-images.githubusercontent.com/52337226/202846224-8f7f7e1d-998a-4bb0-9c3f-4a5cad1834b9.png">
> 
> <img alt="image" width="1137" src="https://user-images.githubusercontent.com/52337226/202846236-483d0f60-0f0e-4407-bb72-033aa438e624.png">
> 
> 链接形式：![[Pasted image 20221119182548.png]] @renmu123

贴一下这部分的配置
![image](https://user-images.githubusercontent.com/26896790/202847176-a7c42c25-d86c-46e7-bd7d-1efa18cfb9c4.png)

**Comment by renmu123** [comment]
> 

不支持 ”内部笔记类型“ 为 “尽可能短” 类型

**Comment by xiuqiang1995** [comment]
> > 
> 
> 不支持 ”内部笔记类型“ 为 “尽可能短” 类型

感谢。是这个问题，已经可以成功上传图片了。
我又回去翻了下 readMe 确实有提到这点：
支持相对路径以及绝对路径，需要进行正确设置，不然会引发奇怪的问题

不过之前没有意识到是这个设置，建议将该设置的图片加入到 readme 中。
再次感谢。

**Comment by renmu123** [comment]
> > > 
> > 
> > 
> > 不支持 ”内部笔记类型“ 为 “尽可能短” 类型
> 
> 感谢。是这个问题，已经可以成功上传图片了。 我又回去翻了下 readMe 确实有提到这点： 支持相对路径以及绝对路径，需要进行正确设置，不然会引发奇怪的问题
> 
> 不过之前没有意识到是这个设置，建议将该设置的图片加入到 readme 中。 再次感谢。

3.0.0版本已经支持了

**Comment by yongxiangzheng** [comment]
3.3.1版本也存在上传本地文件，显示“没有解析到图像文件”，配置如下：
![image](https://user-images.githubusercontent.com/8653159/233785292-36380444-8b47-40e6-a3b1-4c6fe1796ebb.png)

![image](https://user-images.githubusercontent.com/8653159/233785361-ba3203cc-9eb5-4408-a14d-78c59b4eaa65.png)

![image](https://user-images.githubusercontent.com/8653159/233785284-07de71ba-c5cc-4804-911e-0028cc275c7e.png)

**Comment by renmu123** [comment]
> 3.3.1版本也存在上传本地文件，显示“没有解析到图像文件”，配置如下： ![image](https://user-images.githubusercontent.com/8653159/233785292-36380444-8b47-40e6-a3b1-4c6fe1796ebb.png)
> 
> ![image](https://user-images.githubusercontent.com/8653159/233785361-ba3203cc-9eb5-4408-a14d-78c59b4eaa65.png)
> 
> ![image](https://user-images.githubusercontent.com/8653159/233785284-07de71ba-c5cc-4804-911e-0028cc275c7e.png)

你图片文件最后的那个"_SSH生成"是什么语法，大概率是因为这个原因

**Comment by yongxiangzheng** [comment]
这个是用local image plus 插件下载其他图床的图片到本地自动生成的，跟这个没关系，我要是把附件文件夹设置到当前笔记的子文件夹下就能正常上传
