### ISSUE TITLE
与Excel to Markdown Table插件同时工作出现问题

### ISSUE THREAD

**Issue by HiramYang** [renmu123/obsidian-image-auto-upload-plugin#51]
Excel to Markdown Table是一个将Excel表格、csv等，复制粘贴到Obsidian中时，自动转换为对应表格的插件。

问题：
当两个插件同时工作时，且image auto upload plugin的剪切板自动上传功能开启，从Excel复制内容到Obsidian中粘贴，会将内容识别为图片上传，并且将内容转换为对应表格。因此同时出现了图片和表格。两个插件都工作了。

请问这种情况如何解决？

**Comment by renmu123** [comment]
https://github.com/renmu123/obsidian-image-auto-upload-plugin/issues/49 
升到 2.7.0，关闭最后一个选项

**Comment by HiramYang** [comment]
问题解决，麻烦大神了，谢谢！
