### ISSUE TITLE
能否增加对于单个笔记或全部笔记操作的选项

### ISSUE THREAD

**Issue by mofanx** [renmu123/obsidian-image-auto-upload-plugin#52]
![image](https://user-images.githubusercontent.com/93850573/195041184-e19712ea-5dc3-4427-9261-f0bf4508194e.png)

不知道目前的设置，是针对全部笔记，还是编辑中的单个笔记？希望能增加相应的选项，因为部分图片可能并不想上传到图床。感谢！

**Comment by HiramYang** [comment]
好像是针对当前编辑的笔记。

**Comment by HiramYang** [comment]
对

**Comment by renmu123** [comment]
所有的操作都是针对当前笔记的，我之后考虑换一下描述
