### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by HiramYang** [renmu123/obsidian-image-auto-upload-plugin#53]
作者你好
该插件能否增加对于多个md文件上传本地图片的功能，在上传后最好可以选择是否自动删除原有的本地图片。

**Comment by YakshaChien** [comment]
复议，建议原本的本地图片自动整理到一个备份文件夹，而不是删除。

**Comment by ycbrd** [comment]
+1，也需要这个功能！

**Comment by renmu123** [comment]
要上传多个md文件，交互比较难处理，我可以考虑做单个文件夹中所有图片的上传，或者整个资料库图片的上传，以及上传后删除源文件的功能，但是优先级不会很高

**Comment by ycbrd** [comment]
感谢有此计划！

**Comment by renmu123** [comment]
上传后删除源文件的功能上了3.1.0版本

**Comment by ycbrd** [comment]
谢谢您！

**Comment by ycbrd** [comment]
> 上传后删除源文件的功能上了3.1.0版本

既然支持了上传后删除本地源文件，请问技术上能否实现下载后删除图床的文件？如果均能做到可以很好避免文件冗余。

**Comment by renmu123** [comment]
> > 上传后删除源文件的功能上了3.1.0版本
> 
> 既然支持了上传后删除本地源文件，请问技术上能否实现下载后删除图床的文件？如果均能做到可以很好避免文件冗余。

做不到
