### ISSUE TITLE
能否增加手动上传已经生成好的md文件内图片的功能？

### ISSUE THREAD

**Issue by ljq29** [renmu123/obsidian-image-auto-upload-plugin#57]
在安装好插件之前就已经创建过 不少的文档，而因为插件是粘贴图片的时候才会上传，旧有的文档不会自动更新。
typora的图片上传插件可以选择将当前的文件夹内容全部上传网站。

**Comment by m430** [comment]
很需要这个功能。历史文档的图片都是本地的，需要传到图床啊

**Comment by renmu123** [comment]
https://github.com/renmu123/obsidian-image-auto-upload-plugin/blob/master/readme-zh.md#%E6%89%B9%E9%87%8F%E4%B8%8A%E4%BC%A0%E4%B8%80%E4%B8%AA%E6%96%87%E4%BB%B6%E4%B8%AD%E7%9A%84%E6%89%80%E6%9C%89%E5%9B%BE%E5%83%8F%E6%96%87%E4%BB%B6
