### ISSUE TITLE
能否增加本地图片地址替换的功能？

### ISSUE THREAD

**Issue by ljq29** [renmu123/obsidian-image-auto-upload-plugin#59]
有的时候虽然希望能够上传到远程oss上，但是也经常在本地查看图片。如果全部上传到网站上，查看的速度也会相应地拖慢。
markdown的语法能否支持一张图片写2个地址，一个本地一个远程，优先使用本地的地址解析，如果本地没有再查看远程地址？
插件是否可以增加这样的功能？

**Comment by renmu123** [comment]
标准md不支持，ob的wiki也不支持
