### ISSUE TITLE
从粘贴板上传后，url被转义，导致无法正确展示图片

### ISSUE THREAD

**Issue by donway19** [renmu123/obsidian-image-auto-upload-plugin#60]
## 问题描述
1. 从剪贴板粘贴到输入区，触发上传
2. 因获得的链接被转义，无法正确显示图片
![image](https://user-images.githubusercontent.com/49800422/197484830-f2391828-3d8a-40df-81fa-12a020d35d36.png)

版本信息：
Obsidian：v1.0.0
插件版本：v2.7.0
PicGo版本：2.3.1-beta7

## 插件设置
![image](https://user-images.githubusercontent.com/49800422/197484933-49a18a2e-672d-417d-bf17-cdcaac8510ac.png)

## PicGo设置
![image](https://user-images.githubusercontent.com/49800422/197485133-b828cb67-9679-46d0-896d-9b1adfe1a51f.png)
![image](https://user-images.githubusercontent.com/49800422/197485444-f2f18fb0-f198-48c0-9d82-7d9c3b7185d5.png)

**Comment by donway19** [comment]
补充：
v2.3.0无此问题

**Comment by LeiGuo0812** [comment]
一样的配置，遇到了同样的问题

**Comment by renmu123** [comment]
> 一样的配置，遇到了同样的问题

临时解决方案结束使用2.3.0的picgo版本

我win端不能复现，使用 picgo 自带的剪贴板图片上传看一下链接是否正常，如果还是被转义的去 picgo 那里提issue。
![image](https://user-images.githubusercontent.com/26896790/198832169-8264e255-072a-46f4-97c5-0f0632a14dff.png)

**Comment by LeiGuo0812** [comment]
> 

windows PicGo 换成2.30版本解决了，感谢！
