### ISSUE TITLE
在obsidian黏贴图片，生成的文本是转义之后的网址，无法直接使用

### ISSUE THREAD

**Issue by RabbitMeatMeat** [renmu123/obsidian-image-auto-upload-plugin#61]
![image](https://user-images.githubusercontent.com/7726258/197930332-5713b29a-b9eb-4d2a-817b-a18ff200063b.png)
https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2F%2FRabbitMeatMeat%2Fpicture%2Fimage%2F202210261149156.png

**Comment by renmu123** [comment]
#60

**Comment by qazxcdswe123** [comment]
https://github.com/Molunerfinn/PicGo/releases/tag/v2.3.1-beta.8
在新版中修复了此问题
