### ISSUE TITLE
剪辑的微博文章中的图片下载失败

### ISSUE THREAD

**Issue by Broadchurch95** [renmu123/obsidian-image-auto-upload-plugin#62]
![01](https://user-images.githubusercontent.com/101993580/200000578-1004337a-519d-4459-b18f-6b9b8a5a9bcd.png)
![02](https://user-images.githubusercontent.com/101993580/200000595-700ac228-ec53-4f0c-a3dc-1817e903ac0a.png)
请问这个是什么原因呢

**Comment by renmu123** [comment]
因为这个图片的链接没有拓展名，所以没有被认为是图片

**Comment by renmu123** [comment]
3.4.0更新
