### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by narugakuru** [renmu123/obsidian-image-auto-upload-plugin#68]
The security model is closed,Unable to start the plug-in for unknown reasons.
version1.0.3
Installation program version v0.13.23

![image](https://user-images.githubusercontent.com/52521481/204339298-57c0b736-c019-4faf-a13c-0638c12997c1.png)
![image](https://user-images.githubusercontent.com/52521481/204338604-ac3d10da-fa1e-43a7-b03c-ad8e2d6aabb6.png)

**Comment by renmu123** [comment]
你应该要升级你的ob版本了，我目前也不知道最低支持到哪个版本的ob

**Comment by narugakuru** [comment]
非常感谢，升级了ob最新版已经解决了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "renmu123/obsidian-image-auto-upload-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月7日(星期三) 中午11:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [renmu123/obsidian-image-auto-upload-plugin] Failed to load plugin (Issue #68)





 
你应该要升级你的ob版本了，我目前也不知道最低支持到哪个版本的ob
