### ISSUE TITLE
上传图片失败

### ISSUE THREAD

**Issue by FeiLZX3Km** [renmu123/obsidian-image-auto-upload-plugin#69]
主要有以下几个问题：
1. 无论是在笔记阅读模式或者编辑模式，使用Image auto upload Plugin: Upload all images的插件功能，都会显示“没有解析到图像文件”，打开OSS后台，图片确实未能上传。
2.从本地复制任意一张图片，点击命令Image auto upload Plugin: Upload all images，打开OSS后台，图片确实未能上传。
3.在编辑模式下，针对图片-右键-upload, 提示Not support undefined mode

**Comment by FeiLZX3Km** [comment]
> 主要有以下几个问题：
> 
> 1. 无论是在笔记阅读模式或者编辑模式，使用Image auto upload Plugin: Upload all images的插件功能，都会显示“没有解析到图像文件”，打开OSS后台，图片确实未能上传。
>    2.从本地复制任意一张图片，点击命令Image auto upload Plugin: Upload all images，打开OSS后台，图片确实未能上传。
>    3.在编辑模式下，针对图片-右键-upload, 提示Not support undefined mode

似乎排查出了问题，应该是未能设置成绝对路径或者是相对路径所致。

**Comment by FeiLZX3Km** [comment]
诶……是我太蠢了，搞不明白这些设置……劳驾开发者帮忙看一下这是怎么回事。
服务器我配的阿里云OSS，一些偏的设置比如说权限设置我也设置成公读了。图片复制粘贴回来能展示出来，是没问题的。 

![image](https://user-images.githubusercontent.com/21981195/205479642-cdd49204-910b-4243-a70e-34c3c526304b.png)
![image](https://user-images.githubusercontent.com/21981195/205479654-329a037f-3081-439a-8203-f4f64c9ba07f.png)
![image](https://user-images.githubusercontent.com/21981195/205479673-ba582cb2-4c1e-4483-bac6-fb204badc795.png)

**Comment by renmu123** [comment]
目前不支持设置为 最短路径，你变更设置后需要重新黏贴才会变更为新格式。
之后我会考虑支持最短路径，主要还没去搞明白最短路径的图片加载顺序

**Comment by FeiLZX3Km** [comment]
> 目前不支持设置为 最短路径，你变更设置后需要重新黏贴才会变更为新格式。 之后我会考虑支持最短路径，主要还没去搞明白最短路径的图片加载顺序

我试了一下，还真得是。
_您这边是否知道，尽可能更加方便地使原来的短路径改为新格式的方法？_我有许多日记、阅读笔记之类的加了不少图片。一张一张纯手动粘贴可能比较麻烦。

**Comment by renmu123** [comment]
据我所知好像没有这种插件，你要不等等，我这两周里处理一下最短路径图片的上传

**Comment by FeiLZX3Km** [comment]
> 据我所知好像没有这种插件，你要不等等，我这两周里处理一下最短路径图片的上传

我挪了三本书的阅读笔记，累死我了。看着日记我都说不出话来了。我现在立刻停手等着您的好消息。

还有，不知道咱这个插件未来能否支持上传视频并生成视频链接？（如果服务器允许的话）

**Comment by renmu123** [comment]
因为上传走得是picgo，如果picgo可以支持的话，我可以放开可上传的格式

**Comment by renmu123** [comment]
3.0.0版本已经支持所有类型了，有bug再反馈
