### ISSUE TITLE
右键鼠标菜单中是否能够增加一个图标

### ISSUE THREAD

**Issue by kamusis** [renmu123/obsidian-image-auto-upload-plugin#7]
![image](https://user-images.githubusercontent.com/1849506/138637294-afb7973e-c4b9-4126-9959-0b5166c7c56f.png)
upload菜单项非常贴心，但是只有这一个菜单项前面没有图标，看上去很别扭，能否增加一个图标呢？

**Comment by renmu123** [comment]
![image](https://user-images.githubusercontent.com/26896790/141293526-83472425-33c9-4331-a5e2-377d6200d51d.png)

**Comment by kamusis** [comment]
Thank you for the works, "Check for updates" in obsidian can't find the new version yet.

**Comment by renmu123** [comment]
It will be updated tomorrow with other fix.

**Comment by renmu123** [comment]
update

**Comment by kamusis** [comment]
Great! Updated and got the icon, but … maybe a little OCD, if can change “upload” to “Upload”, will be 100% perfect :-D

--
Kamus ***@***.***>
在 2021年11月12日 +0900 12:38，renmu123 ***@***.***>，写道：

**Comment by renmu123** [comment]
Thanks for your suggestion, it will be updated in next version
