### ISSUE TITLE
域名黑名单无法使用

### ISSUE THREAD

**Issue by shuojie819** [renmu123/obsidian-image-auto-upload-plugin#73]
Image auto upload Plugin版本：3.0
Obsidian版本：1.0.3

设置域名黑名单无效，不知是不是我的格式有误
```
图片：![image-20220106010532325](https://cos.shuojie819.top/obsidian/202212182318495.png?imageMogr2/format/webp/interlace/1)

黑名单格式：（均无法使用）
https://cos.shuojie819.top
cos.shuojie819.top
shuojie819.top
```

**Comment by renmu123** [comment]
比如说这个图片 `![](https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png)`
你设置为 `githubassets.com`或者`github.githubassets.com`都是可以的，不需要添加协议，~~你甚至可以设置成`githubassets`~~。

我测试了你的例子，使用 `cos.shuojie819.top`或者`shuojie819.top`都是可以生效的

3.0.0版本中 在未设置黑名单的情况下，所有网络图片均无法上传的问题，在3.0.1版本中修复

**Comment by shuojie819** [comment]
还是以上语法
Image auto upload Plugin：3.0.1
Obsidian：1.1.9

图片：`![image.png](https://cos.shuojie819.top/obsidian/202301031639568.png?imageMogr2/format/webp/interlace/1)`
附加一个黑名单无效的[GIF](https://cos.shuojie819.top/obsidian/OB-auto%20Image%20%E9%BB%91%E5%90%8D%E5%8D%95BUG.gif)
因超过了10M请点击[GIF](https://cos.shuojie819.top/obsidian/OB-auto%20Image%20%E9%BB%91%E5%90%8D%E5%8D%95BUG.gif)查看

**Comment by renmu123** [comment]
我知道，针对这个功能我忘记处理黑名单了，我还以为你说得是批量上传时这个功能坏了呢，下个版本修

**Comment by shuojie819** [comment]
哦哦，好的☺️
