### ISSUE TITLE
Download command doesn't work

### ISSUE THREAD

**Issue by vanbang9710** [renmu123/obsidian-image-auto-upload-plugin#79]
All other features work perfectly except this
![image](https://user-images.githubusercontent.com/52906188/215848777-59cd3cf3-fbc3-4fa4-85a7-acd514b75fe7.png)

**Comment by renmu123** [comment]
l filter the `.webp` format image ( ´•̥̥̥ω•̥̥̥` ).
More image format will be support in next version.
