### ISSUE TITLE
无法批量上传

### ISSUE THREAD

**Issue by maxhytv** [renmu123/obsidian-image-auto-upload-plugin#8]
每次输入批量上传命令，picgo都会提示：请检查配置和文件……

---
使用其他功能都无影响

**Comment by renmu123** [comment]
你更新下picgo版本试试看

**Comment by johnsonsuqs** [comment]
请问解决了吗？我开始安装2.30批量下载无效，没有任何提示，然后升到2.3.1还没有效果。批量下载会报错全部下载失败，然后整个文章全部清空。

**Comment by maxhytv** [comment]
已经解决，感谢
