### ISSUE TITLE
请求增加排除文件夹功能

### ISSUE THREAD

**Issue by SEELE0** [renmu123/obsidian-image-auto-upload-plugin#81]
希望可以更新一个排除特定文件夹的功能，方便在同一个笔记库下编辑私人文件，私人文件里的图片自动上传到图床有些担心隐私问题

**Comment by renmu123** [comment]
https://github.com/renmu123/obsidian-image-auto-upload-plugin/blob/master/readme-zh.md#%E5%89%AA%E5%88%87%E6%9D%BF%E4%B8%8A%E4%BC%A0

设置笔记的元数据，可以达到你要的效果
---
image-auto-upload: false
---
