### ISSUE TITLE
一个奇怪的问题，上传其它图片会变成刚刚上传过的图片

### ISSUE THREAD

**Issue by Halecoder** [renmu123/obsidian-image-auto-upload-plugin#82]
[](https://streamja.com/zBzjk)

**Comment by Halecoder** [comment]
https://streamja.com/zBzjk

**Comment by renmu123** [comment]
应该是有同名图片引起的，之后可以针对基于根目录的图片路径做一下优化，你可以先试试右键图片有个`Upload`上传单个图片有没有问题，这两个实现逻辑不太一样
PS：其实主要是ob的附件解析是有问题的，我又不知道他的解析规则，导致有时候会有解析错误

**Comment by Halecoder** [comment]
> 应该是有同名图片引起的，之后可以针对基于根目录的图片路径做一下优化，你可以先试试右键图片有个`Upload`上传单个图片有没有问题，这两个实现逻辑不太一样 PS：其实主要是ob的附件解析是有问题的，我又不知道他的解析规则，导致有时候会有解析错误

传单个没有问题

**Comment by Halecoder** [comment]
> 应该是有同名图片引起的，之后可以针对基于根目录的图片路径做一下优化，你可以先试试右键图片有个`Upload`上传单个图片有没有问题，这两个实现逻辑不太一样 PS：其实主要是ob的附件解析是有问题的，我又不知道他的解析规则，导致有时候会有解析错误

谢谢，我再看看把，请问还有没有这样的插件，批量借助picgo上传一个md文档的所有图片

**Comment by renmu123** [comment]
据我所知，ob生态下没有了，你可以试试typora，但是你的文件都是基于ob库的绝对路径，typora好像只支持相对路径

**Comment by Halecoder** [comment]
> 更新了一版优化了绝对路径文件的上传，ob附件的解析模式确实有变更了。

辛苦了，谢谢

**Comment by Halecoder** [comment]
> 更新了一版优化了绝对路径文件的上传，ob附件的解析模式确实有变更了。
咳咳，大哥，要不麻烦你试下先粘贴上传张图片，然后再整体上传下试试，我这个单击上传和整体上传都是刚刚剪切板上传的图片
,哭了，不会是我自己问题吧，不好意思

**Comment by Halecoder** [comment]
结案了，一定要使用相对路径
