### ISSUE TITLE
关闭上传后自动删除库里的图片后,粘贴的图片还是无法保存到库中

### ISSUE THREAD

**Issue by TianShan95** [renmu123/obsidian-image-auto-upload-plugin#86]
系统-macos12.3，插件用的app模式
我关闭插件或者关闭剪切板自动上传之后可以在obsidian的库中看到我粘贴的图片，但是打开插件再粘贴图片就不自动保存到本地库了。上传云和保存本地只能二选一吗？
我尝试重新安装插件和picgo软件都没有解决问题，请指教。

**Comment by TianShan95** [comment]
<img width="822" alt="截屏2023-03-18 17 08 19" src="https://user-images.githubusercontent.com/67675520/226096375-373b2d4b-ee2d-45a7-b104-2a4c34679c11.png">

**Comment by renmu123** [comment]
是这样的，在黏贴图片时，会禁用掉ob原有的插入文件逻辑，导致无法保存到库中。
你可以尝试关闭自动上传，采用`upload all images`命令来进行手动上传文件
