### ISSUE TITLE
添加对 PicList 的支持

### ISSUE THREAD

**Issue by LeiGuo0812** [renmu123/obsidian-image-auto-upload-plugin#87]
PicList 是一款云存储/图床平台管理和文件上传工具，基于 PicGo 进行了深度二次开发，但功能更强大（可以访问删除图床中的文件）

文档网址：https://piclist.cn/app.html
github地址：https://github.com/Kuingsmile/PicList/releases

下载后使用相同的配置，但是无法实现ob粘贴上传，请问作者能否添加一下对 PicList 软件的支持？感谢！

**Comment by 2019YKL** [comment]
我也是用Piclist，但是没有复现你所述的问题。你看看是否图床设置出了问题。
