### ISSUE TITLE
Feature wanted: PicList 同步删除功能支持 已添加Pull Request

### ISSUE THREAD

**Issue by Kuingsmile** [renmu123/obsidian-image-auto-upload-plugin#89]
[PicList](https://github.com/Kuingsmile/PicList)是由我开发的基于PicGo的二次开发版，完全兼容所有PicGo功能和本插件，此外，在V1.5.2版本之后，新增了一个/delete api接口，可用于http调用删除PicList相册内的图片，如果开启了云端删除功能，还可以同步删除云端的图片。

该接口和本插件对接使用，可以实现在需要删除或修改图片时，快速同步删除云端的文件，方便使用，提高效率。
![image](https://user-images.githubusercontent.com/96409857/228225904-47520cf9-81fc-4ea4-aa62-990487ef6c53.png)

![image](https://user-images.githubusercontent.com/96409857/228225874-4c959826-32a8-4d79-87cd-b435f40fd176.png)

基于该需求，我已fork本仓库并添加了对应功能，通过右键菜单的形式实现，已经提交了PR，希望作者大大可以审核，并考虑merge进来~

PR里没有破坏目前该插件已有的任何功能，在使用PicGo时，也不会导致出现bug~

**Comment by renmu123** [comment]
#88

**Comment by FightingFZC** [comment]
我想问问能不能让配置PicList同步删除和配置PicGo-Core一样
![image](https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/74097223/b6c4f154-c991-4c1f-b6ec-c5bc30ed12f3)
这样就可以不打开PicList（PicGo）实现上传/删除了……

**Comment by Kuingsmile** [comment]
> 我想问问能不能让配置PicList同步删除和配置PicGo-Core一样 ![image](https://user-images.githubusercontent.com/74097223/249028937-b6c4f154-c991-4c1f-b6ec-c5bc30ed12f3.png) 这样就可以不打开PicList（PicGo）实现上传/删除了……

删除功能目前在piclist里实现的，core不支持

**Comment by FightingFZC** [comment]
好吧，了解了，感谢回复！
