### ISSUE TITLE
点击“upload”按钮上传成功，但不替换原文

### ISSUE THREAD

**Issue by meta-tabchen** [renmu123/obsidian-image-auto-upload-plugin#9]
如图，使用命令上传所有的图片，也是同样问题。
![image](https://user-images.githubusercontent.com/19347690/143326733-afba355d-a693-4d64-98e9-e4da574d6685.png)

**Comment by tangyuan233** [comment]
+1，我也遇到了这个问题，上传成功但还是粘贴的那个图片不是github的url

**Comment by renmu123** [comment]
目前只支持标准的markdown超链接语法，不支持wiki
