### ISSUE TITLE
粘贴剪贴板中的图片，上传前修改文件名，并没有体现在结果的markdown中，都是image.png

### ISSUE THREAD

**Issue by mobilestack** [renmu123/obsidian-image-auto-upload-plugin#91]
能否使用改名上传后的回传结果来展示改名后的markdown

现在都是这样的
<img width="333" alt="image" src="https://user-images.githubusercontent.com/5794691/230595601-ff677511-59f0-401f-b341-bd1668c6ca3b.png">

<img width="563" alt="image" src="https://user-images.githubusercontent.com/5794691/230595296-41a89b05-2bba-4f3c-af77-e9d52386a5b3.png">

**Comment by renmu123** [comment]
这个名称默认是上传前的的图片名称，我之后会加个选项允许修改为上传后的图片名称

**Comment by oneyangcrown** [comment]
图片描述能不能默认为空，现在粘贴图片都要去手动删除一下这个image.png @renmu123

**Comment by timerring** [comment]
> 图片描述能不能默认为空，现在粘贴图片都要去手动删除一下这个image.png @renmu123

认同，这个特性对于将文章同步到一些常显示图片标题的网站（如知乎）很重要，每次同步文章到知乎之前，都要手动去除每个图片的image.png标题属性，实在过于不方便。 @renmu123

**Comment by renmu123** [comment]
已经在3.5.0中增加配置选项

**Comment by yslin1995** [comment]
> 这个名称默认是上传前的的图片名称，我之后会加个选项允许修改为上传后的图片名称

大佬，现在4.1.0版本好像还是统一为image.png

**Comment by kettly1260** [comment]
是统一为image.png是，每次剪切板上传的图片最后会变成同一张图片
