### ISSUE TITLE
上传所有图片时无法忽略网络照片

### ISSUE THREAD

**Issue by pt-99** [renmu123/obsidian-image-auto-upload-plugin#93]
在选项中设置了忽略网络位置照片后依然会检测到并上传图床链接的照片，造成重复上传的问题
已经尝试卸载重装插件
picgo v2.3.1
插件相关设置：
![Snipaste_2023-04-14_07-49-57](https://user-images.githubusercontent.com/120309950/231907073-cc2f23a0-1747-4b08-b1cf-fdc60cbaa313.png)
文件中已有图床格式链接
![Snipaste_2023-04-14_07-58-22](https://user-images.githubusercontent.com/120309950/231908905-da26cb13-82b6-49d7-b364-b4239f4b544c.png)
上传所有文件指令后依然识别了这个网络照片：
![Snipaste_2023-04-14_07-58-41](https://user-images.githubusercontent.com/120309950/231908275-f9f64528-3f5d-4f9e-9bef-f8bc9317a577.png)
图床中出现了第二次重新上传的照片：
![Snipaste_2023-04-14_07-59-53](https://user-images.githubusercontent.com/120309950/231908285-7d383f44-6ad2-44d1-af4b-c699839861e5.png)

**Comment by renmu123** [comment]
3.3.1修复
