### ISSUE TITLE
没有找到右键删除图片按钮

### ISSUE THREAD

**Issue by Curry30huang** [renmu123/obsidian-image-auto-upload-plugin#94]
![image](https://user-images.githubusercontent.com/68208371/233316242-9c9f110a-72b4-4899-8cf8-867178fdb1b3.png)

没有找到按键，无法使用删除图床图片功能

**Comment by renmu123** [comment]
只有使用通过picList上传的图片才能删除图片

**Comment by Curry30huang** [comment]
我是的就是 obsidian 调用 picList 进行批量上传的得到的图片呀
![image](https://user-images.githubusercontent.com/68208371/233329012-91106d70-65c2-4c22-be7b-c2ff6d75b8dc.png)

**Comment by renmu123** [comment]
3.3.1修复
