### ISSUE TITLE
下载图片时文件名被更改和链接被改为本地

### ISSUE THREAD

**Issue by qiwuteng** [renmu123/obsidian-image-auto-upload-plugin#95]
图片下载后，文件名会被加前缀 image-，能否添加选项取消该前缀，下载后还会默认将文件中的图片链接改为本地，能否支持不被改为本地链接，谢谢

**Comment by renmu123** [comment]
命名下个版本会改。
你可以下载后按ctrl+z进行撤销，这个功能的本意是将网络图片链接转换为本地，而不是一个下载md中图片的工具

**Comment by renmu123** [comment]
3.3.1修复
