### ISSUE TITLE
不能识别omnivore导入的笔记中的图片链接。

### ISSUE THREAD

**Issue by zhcbbs** [renmu123/obsidian-image-auto-upload-plugin#96]
omnivore导入网页后，会对图片链接进行特殊处理，加上一个https://proxy-prod.omnivore-image-cache.app/  信息，虽然不影响ob正常显示照片，但插件不能识别这个链接，导致下载或上传图床失败。

**Comment by renmu123** [comment]
给个示例链接我瞧瞧

**Comment by zhcbbs** [comment]
https://proxy-prod.omnivore-image-cache.app/0x0,sb-VItn4PFYcrCobIirKAWzlntYSOWd0SCjTPbg5-3VQ/https://img.36krcdn.com/hsossms/20230511/v2_1e2c1f5b7dc1485c854965bb426f8c8c@000000_oswg889715oswg1080oswg533_img_000

https://proxy-prod.omnivore-image-cache.app/0x0,sc-qrGMQW9dzfi2WoF0U7VxouZsaRaBW1DBfjNVEwu3E/https://cdn.sspai.com/2023/05/09/article/29f7caf15abce177b7937cade2226dab?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1


例如这样的链接

**Comment by zhcbbs** [comment]
https://omnivore.app    剪藏工具剪藏网页后，图片链接被修改成上面的样式，web浏览器和ob中都能正常显示，但是image插件不能下载图片，似乎不识别link。

**Comment by renmu123** [comment]
不能下载可能因为我解析了http图片的后缀，只有判断为图片的后缀才会进行下载。
ob自带的请求库，获取不了请求的content-type，我之后再换回三方的库吧。
正则匹配怎么还要换🥲

**Comment by zhcbbs** [comment]
3.4.1已经更新了这个问题么？回家更新至3.4.1，可以上传omnivore的图片了。

**Comment by renmu123** [comment]
> 3.4.1已经更新了这个问题么？回家更新至3.4.1，可以上传omnivore的图片了。

理论上可以了，但是你要注意上上面我提到的ob的bug。
具体操作你还是需要先执行下载命令再执行上传命令，上传网络图片我不确定能否支持，这是图床软件的功能。

**Comment by zhcbbs** [comment]
图床是支持的这个格式链接的，您是修改代码兼容omnivore 种这种特殊格式图片链接了么？我现在直接用 upload  all 指令就能直接上传图床了

**Comment by zhcbbs** [comment]
https://www.wenshushu.cn/f/b7il5djea4f

这个从omnivore导入的文档，新版插件还是无法识别下载，总是反馈下载错误。

**Comment by renmu123** [comment]
> https://www.wenshushu.cn/f/b7il5djea4f
> 
> 这个从omnivore导入的文档，新版插件还是无法识别下载，总是反馈下载错误。

我不清楚你说的”下载错误“是什么意思，是有什么报错还是其他的问题。
![image](https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/26896790/65fd782c-0dd7-4e96-85bb-3eb657ad26b8)

我试了一下是可以下载成功的，只不过所有文件都被命名成了640.png，这是另外一个bug导致的

**Comment by zhcbbs** [comment]
确实，download all images 时，显示下载成功，不能页面所有图片都变成同样的了。如果直接使用 upload all images，反馈是这种错误

<img width="202" alt="image" src="https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/4313046/f4c0a77b-ad42-474a-9ad4-562baeda2cb3">

测试文件原链接失效了，我重新用dropbox分享一下，看看能否修正这个bug。

https://www.dropbox.com/s/m4a2t8bn5yw4cm9/%E5%9F%BA%E4%BA%8EGPT3.5%E6%90%AD%E5%BB%BA%E5%AE%9A%E5%88%B6%E5%8C%96%E7%9F%A5%E8%AF%86%E5%BA%93.md?dl=0

**Comment by renmu123** [comment]
> 确实，download all images 时，显示下载成功，但是页面内所有图片都变成同样的了，应该是重名bug造成的。 如果直接使用 upload all images，反馈是upload error，以下是截图。
> 
> <img alt="image" width="202" src="https://user-images.githubusercontent.com/4313046/238665234-f4c0a77b-ad42-474a-9ad4-562baeda2cb3.png">
> 测试文件原链接失效了，我重新用dropbox分享一下，看看能否修正这个bug。
> 
> https://www.dropbox.com/s/m4a2t8bn5yw4cm9/%E5%9F%BA%E4%BA%8EGPT3.5%E6%90%AD%E5%BB%BA%E5%AE%9A%E5%88%B6%E5%8C%96%E7%9F%A5%E8%AF%86%E5%BA%93.md?dl=0

我已经修过一版了，你更新后再尝试一下

**Comment by renmu123** [comment]
我尝试了download all image 后 upload 是可行的，你设置应用网络图片后使用upload all images，这个行为是图床软件（如picgo）的实现，我这里控制不了，你可以去相应的仓库提issue

**Comment by zhcbbs** [comment]
好的，明白了

**Comment by zhcbbs** [comment]
和picgo作者联系，主要原因是调用picgo-core时，链接中存在非法字符，需要做转义处理，可能还是需要插件提前将链接中不能直接转递给pcigo的字符做转义处理，才行。例如：
注意看可以上传的链接长这样（注意看结尾部分）：

转义后链接：    https://proxy-prod.omnivore-image-cache.app/0x0,sgTCFY-0eJ5F8gzIHhH85pqxGFaPoefxDjrUOUglgka8/https://mmbiz.qpic.cn/mmbiz_png/VXdFUnbrlOhuVhkrTSq7l5rnpWmsE27XgyviaRqzO9AYSRmL2pTiciaHrpOl6Xp5oetOgCUPuYTNks6k29Zye63qg/640\?wx_fmt\=png


原始链接：
https://proxy-prod.omnivore-image-cache.app/0x0,sgTCFY-0eJ5F8gzIHhH85pqxGFaPoefxDjrUOUglgka8/https://mmbiz.qpic.cn/mmbiz_png/VXdFUnbrlOhuVhkrTSq7l5rnpWmsE27XgyviaRqzO9AYSRmL2pTiciaHrpOl6Xp5oetOgCUPuYTNks6k29Zye63qg/640?wx_fmt=png

**Comment by zhcbbs** [comment]
具体讨论见：  https://github.com/PicGo/PicGo-Core/issues/153

**Comment by renmu123** [comment]
我可以来做转义，但是还有一个问题，你尝试一下多传几张你这种格式的图片，你会发现最后返回的url是相同的（可能是图片被命名为url的最后一串了）
![image](https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/26896790/ed33dfe5-f077-4b0c-b0cf-03c68036c86c)

**Comment by zhcbbs** [comment]
https://github.com/PicGo/PicGo-Core/files/11488917/GPT3.5.md

您看看这个测试文档里面链接。

我的用的图床每次会返还随机的文件名，应该不受影响吧？

**Comment by zhcbbs** [comment]
奇怪，现在您的插件和picgo都没问题，为什么upload 网络图片会报错呢，太奇怪了。

**Comment by renmu123** [comment]
我之后发个版本， 把upload error的log打印出来，看看啥原因报错了

**Comment by zhcbbs** [comment]
好的，多谢

**Comment by zhcbbs** [comment]
又发现一个omnivore剪藏的网页下载图片有问题，你测试一下。

[北京2023年中招时间安排.md](https://github.com/renmu123/obsidian-image-auto-upload-plugin/files/11501252/2023.md)

挑选一个链接：

https://proxy-prod.omnivore-image-cache.app/0x0,srmfUGtj2F_0-rG8gbsQYSX1_SV_x0NSG4NKfKIC40Tk/https://rls3.cj.sina.com.cn/products/202305/e9ee63e1abc436476aed64d966943aba.png

插件报upload error后，使用dwonload all  images，没有下载成功图片。

在终端使用指令：
picgo upload "https://proxy-prod.omnivore-image-cache.app/0x0,srmfUGtj2F_0-rG8gbsQYSX1_SV_x0NSG4NKfKIC40Tk/https://rls3.cj.sina.com.cn/products/202305/e9ee63e1abc436476aed64d966943aba.png"

报错信息：

[PicGo INFO]: Before transform
[PicGo INFO]: Transforming... Current transformer is [path]
[PicGo WARN]: failed
[PicGo ERROR]: Error: request https://proxy-prod.omnivore-image-cache.app/0x0,srmfUGtj2F_0-rG8gbsQYSX1_SV_x0NSG4NKfKIC40Tk/https://rls3.cj.sina.com.cn/products/202305/e9ee63e1abc436476aed64d966943aba.png error, maxContentLength size of Infinity exceeded
    at /opt/homebrew/lib/node_modules/picgo/dist/index.cjs.js:1:38189
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async Object.handle (/opt/homebrew/lib/node_modules/picgo/dist/index.cjs.js:1:37138)
    at async $e.doTransform (/opt/homebrew/lib/node_modules/picgo/dist/index.cjs.js:1:16679)
    at async $e.start (/opt/homebrew/lib/node_modules/picgo/dist/index.cjs.js:1:15916)
    at async Tt.upload (/opt/homebrew/lib/node_modules/picgo/dist/index.cjs.js:1:71270)
    at async /opt/homebrew/lib/node_modules/picgo/dist/index.cjs.js:1:3226

**Comment by zhcbbs** [comment]
又发现一个omnivore剪藏的网页下载图片有问题，你测试一下。

[北京2023年中招时间安排.md](https://github.com/renmu123/obsidian-image-auto-upload-plugin/files/11501252/2023.md)

我拷贝里面的链接，在终端用picgo上传是可以成功的，但是在ob插件中，就会显示upload error错误，您查一下，是不是传递url参数的问题。
