### ISSUE TITLE
应用网络图片BUG

### ISSUE THREAD

**Issue by shuojie819** [renmu123/obsidian-image-auto-upload-plugin#98]
开启“应用网络图片”，并设置网络图片域名黑名单，应用网络图片会失效。

https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/72399630/cdacd321-fd05-4628-85aa-1c60273b3a00

**Comment by zhcbbs** [comment]
我没有这个问题啊

**Comment by renmu123** [comment]
你插件什么版本，我也不能复现

**Comment by shuojie819** [comment]
> 你插件什么版本，我也不能复现

Windows11
Obsidian：v1.2.8
Image auto upload Plugin: v3.3.2
对了我用的是piclist，和这个有关系吗？

**Comment by renmu123** [comment]
~~理论上是没有关系的~~实际上有点关系，我picgo和piclist的测试结果还真不一样。
你可以先尝试把规则最后的英文逗号删了，我再去看看啥究竟原因
![image](https://github.com/renmu123/obsidian-image-auto-upload-plugin/assets/26896790/592a5d68-613e-430c-b45a-d93f859cdff3)

**Comment by shuojie819** [comment]
好的👌，😘
